# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQd7O3Pb6r3FcrWmwgojum0dSa2lVeF_
"""

import pandas as pd

df = pd.read_csv('Electric_Vehicle_Population_Data.csv', encoding='latin-1')

df.head()

from matplotlib import pyplot as plt
_df_82['timeClose'].plot(kind='hist', bins=20, title='timeClose')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_72['timeLow'].plot(kind='line', figsize=(8, 4), title='timeLow')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_27['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)